[package]
name = "fish_greeting_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
colored = "2.0.0"
itertools = "0.10.3"
substring = "1.4.5"
